import { describe, expect, it, vi } from 'vitest';
import {
  buildAutoGeneratedZonePayloads,
  classifyNeighborhoodSuggestions,
  fetchNeighborhoodSuggestionCandidates,
  resolveStoreSuggestionOrigin,
} from '../utils/deliveryZoneSuggestions';

function createJsonResponse(data) {
  return {
    ok: true,
    json: async () => data,
  };
}

describe('deliveryZoneSuggestions', () => {
  it('usa coordenadas da loja como origem principal quando disponiveis', async () => {
    const fetchSpy = vi.fn();
    const origin = await resolveStoreSuggestionOrigin({
      store: {
        latitude: -2.53,
        longitude: -44.28,
        address: 'Rua X, Sao Luis - MA',
      },
      fetchImpl: fetchSpy,
    });

    expect(origin).toMatchObject({
      ready: true,
      source: 'store_coordinates',
      label: 'Coordenadas da loja',
      center: { lat: -2.53, lng: -44.28 },
    });
    expect(fetchSpy).not.toHaveBeenCalled();
  });

  it('faz fallback para geocodificacao do endereco da loja', async () => {
    const fetchSpy = vi.fn(async () => createJsonResponse([
      {
        lat: '-2.5401',
        lon: '-44.3012',
        display_name: 'Av. dos Holandeses, Sao Luis, Maranhao, Brasil',
        address: {
          suburb: 'Calhau',
          city: 'Sao Luis',
          state: 'MA',
        },
      },
    ]));

    const origin = await resolveStoreSuggestionOrigin({
      store: {
        address: 'Av. dos Holandeses, Sao Luis - MA',
      },
      fetchImpl: fetchSpy,
    });

    expect(origin).toMatchObject({
      ready: true,
      source: 'store_address_geocode',
      confidence: 'medium',
      center: { lat: -2.5401, lng: -44.3012 },
      city: 'Sao Luis',
      state: 'MA',
    });
    expect(fetchSpy).toHaveBeenCalledTimes(1);
  });

  it('sugere bairros por amostragem regional e deduplica candidatos equivalentes', async () => {
    const responses = [
      { lat: '-2.5300', lon: '-44.2800', address: { suburb: 'Centro', city: 'Sao Luis', state: 'MA' } },
      { lat: '-2.5310', lon: '-44.2810', address: { suburb: 'Centro', city: 'Sao Luis', state: 'MA' } },
      { lat: '-2.5320', lon: '-44.2820', address: { suburb: 'Renascenca', city: 'Sao Luis', state: 'MA' } },
      { lat: '-2.5330', lon: '-44.2830', address: { suburb: 'Renascenca', city: 'Sao Luis', state: 'MA' } },
      { lat: '-2.5340', lon: '-44.2840', address: { suburb: 'Cohama', city: 'Sao Luis', state: 'MA' } },
      { lat: '-2.5350', lon: '-44.2850', address: { suburb: '', city: 'Sao Luis', state: 'MA' } },
      { lat: '-2.5360', lon: '-44.2860', address: { suburb: 'Calhau', city: 'Sao Luis', state: 'MA' } },
      { lat: '-2.5370', lon: '-44.2870', address: { suburb: 'Calhau', city: 'Sao Luis', state: 'MA' } },
      { lat: '-2.5380', lon: '-44.2880', address: { suburb: '', city: 'Sao Luis', state: 'MA' } },
      { lat: '-2.5390', lon: '-44.2890', address: { suburb: 'Angelim', city: 'Sao Luis', state: 'MA' } },
      { lat: '-2.5400', lon: '-44.2900', address: { suburb: 'Angelim', city: 'Sao Luis', state: 'MA' } },
      { lat: '-2.5410', lon: '-44.2910', address: { suburb: 'Centro', city: 'Sao Luis', state: 'MA' } },
      { lat: '-2.5420', lon: '-44.2920', address: { suburb: 'Cohama', city: 'Sao Luis', state: 'MA' } },
    ];

    let callIndex = 0;
    const fetchSpy = vi.fn(async () => createJsonResponse(responses[callIndex++]));

    const result = await fetchNeighborhoodSuggestionCandidates({
      store: {
        latitude: -2.53,
        longitude: -44.28,
      },
      fetchImpl: fetchSpy,
      radiusKm: 5,
    });

    expect(result.ready).toBe(true);
    expect(result.suggestions.map((item) => item.neighborhood)).toEqual([
      'Centro',
      'Renascenca',
      'Cohama',
      'Calhau',
      'Angelim',
    ]);
    expect(result.sampledPoints).toBe(13);
  });

  it('classifica bairros ja cadastrados e duplicados provaveis antes da criacao', () => {
    const suggestions = classifyNeighborhoodSuggestions([
      { id: 'centro', neighborhood: 'Centro', distanceKm: 0.5 },
      { id: 'renascenca-ii', neighborhood: 'Renascenca II', distanceKm: 1.2 },
      { id: 'calhau', neighborhood: 'Calhau', distanceKm: 2.1 },
    ], [
      { id: '1', neighborhood: 'Centro', fee: 8 },
      { id: '2', neighborhood: 'Renascenca', fee: 9 },
    ]);

    expect(suggestions[0]).toMatchObject({
      neighborhood: 'Calhau',
      status: 'new',
      selectable: true,
    });
    expect(suggestions[1]).toMatchObject({
      neighborhood: 'Renascenca II',
      status: 'probable_duplicate',
      selectable: false,
    });
    expect(suggestions[2]).toMatchObject({
      neighborhood: 'Centro',
      status: 'already_registered',
      selectable: false,
    });
  });

  it('monta payloads auto_generated apenas para sugestoes realmente novas', () => {
    const payloads = buildAutoGeneratedZonePayloads({
      suggestions: [
        {
          id: 'calhau',
          neighborhood: 'Calhau',
          selectable: true,
          city: 'Sao Luis',
          state: 'MA',
          distanceKm: 2.4,
          suggestionSource: 'nominatim_reverse_sample',
          suggestionOrigin: 'store_coordinates',
          suggestionOriginLabel: 'Coordenadas da loja',
        },
        {
          id: 'centro',
          neighborhood: 'Centro',
          selectable: false,
          city: 'Sao Luis',
          state: 'MA',
        },
      ],
      selectedIds: ['calhau', 'centro'],
      defaults: {
        fee: '8.5',
        min_order: '25',
        is_active: true,
        notes: 'Gerado por sugestao',
        generatedAt: '2026-03-30T12:00:00.000Z',
      },
    });

    expect(payloads).toHaveLength(1);
    expect(payloads[0]).toMatchObject({
      neighborhood: 'Calhau',
      source: 'auto_generated',
      fee: 8.5,
      min_order: 25,
      notes: 'Gerado por sugestao',
    });
    expect(payloads[0].source_metadata).toMatchObject({
      generated_at: '2026-03-30T12:00:00.000Z',
      suggestion_source: 'nominatim_reverse_sample',
      suggestion_origin: 'store_coordinates',
      city: 'Sao Luis',
      state: 'MA',
    });
  });
});
