const MEDIA_UPLOAD_PRESETS = {
  product: {
    id: 'product',
    label: 'Produto',
    ratioLabel: '1:1',
    recommendedSize: '800x800',
    aspectRatio: 1,
    outputWidth: 1200,
    outputHeight: 1200,
    focusLabel: 'centro do produto',
    previewLabel: 'Card do cardapio',
    folder: 'dishes',
    title: 'Adicionar foto do produto',
    description: 'Use uma imagem nitida para destacar o item no cardapio.',
  },
  banner: {
    id: 'banner',
    label: 'Banner',
    ratioLabel: '16:9',
    recommendedSize: '1200x675',
    aspectRatio: 16 / 9,
    outputWidth: 1600,
    outputHeight: 900,
    focusLabel: 'faixa horizontal central',
    previewLabel: 'Banner promocional',
    folder: 'store',
    title: 'Adicionar banner',
    description: 'Use uma arte horizontal limpa para comunicar promocoes e campanhas.',
  },
  cover: {
    id: 'cover',
    label: 'Capa',
    ratioLabel: '16:9',
    recommendedSize: '1600x900',
    aspectRatio: 16 / 9,
    outputWidth: 1600,
    outputHeight: 900,
    focusLabel: 'area principal da loja',
    previewLabel: 'Topo da loja',
    folder: 'store',
    title: 'Adicionar capa da loja',
    description: 'Escolha uma imagem horizontal que represente bem a identidade da loja.',
  },
  category: {
    id: 'category',
    label: 'Categoria',
    ratioLabel: '1:1',
    recommendedSize: '800x800',
    aspectRatio: 1,
    outputWidth: 1200,
    outputHeight: 1200,
    focusLabel: 'icone ou prato principal',
    previewLabel: 'Bloco de categoria',
    folder: 'categories',
    title: 'Adicionar imagem da categoria',
    description: 'Use uma imagem simples e clara para reforcar a leitura da categoria.',
  },
  promotion: {
    id: 'promotion',
    label: 'Promocao',
    ratioLabel: '4:5',
    recommendedSize: '1080x1350',
    aspectRatio: 4 / 5,
    outputWidth: 1080,
    outputHeight: 1350,
    focusLabel: 'oferta principal no centro',
    previewLabel: 'Card promocional',
    folder: 'promotions',
    title: 'Adicionar arte promocional',
    description: 'Mantenha o foco na oferta principal e deixe textos importantes na area central.',
  },
  logo: {
    id: 'logo',
    label: 'Logo',
    ratioLabel: '1:1',
    recommendedSize: '500x500',
    aspectRatio: 1,
    outputWidth: 1000,
    outputHeight: 1000,
    focusLabel: 'marca centralizada',
    previewLabel: 'Logo da loja',
    folder: 'store',
    title: 'Adicionar logo',
    description: 'A logo aparece em varios pontos do sistema. Priorize contraste e leitura.',
  },
};

export function getMediaUploadPreset(type = 'product') {
  return MEDIA_UPLOAD_PRESETS[type] || MEDIA_UPLOAD_PRESETS.product;
}

export { MEDIA_UPLOAD_PRESETS };
