import React, { useEffect, useMemo, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import {
  AlertTriangle,
  ArrowUpDown,
  CheckSquare,
  Filter,
  Layers3,
  MapPin,
  Package,
  Plus,
  Search,
  ShieldAlert,
  Sparkles,
  TestTube2,
  Trash2,
  TrendingUp,
  Upload,
} from 'lucide-react';
import EmptyState from '@/components/ui/EmptyState';
import toast from 'react-hot-toast';
import { usePermission } from '../permissions/usePermission';
import { getMenuContextEntityOpts, getMenuContextQueryKeyParts } from '@/utils/tenantScope';
import {
  normalizeNeighborhood,
  resolveCheckoutAddressMode,
  resolveDeliveryHybridStrategy,
  resolveDeliveryPricingMode,
  resolveOutsideAreaBehavior,
} from '@/utils/deliveryRules';
import {
  buildDeliveryZonePayload,
  findDuplicateZoneGroups,
  findEquivalentDeliveryZones,
  normalizeZoneSource,
  parseBulkZonesInput,
  simulateDeliveryCoverage,
} from '@/utils/deliveryZoneAdmin';
import {
  buildAutoGeneratedZonePayloads,
  classifyNeighborhoodSuggestions,
  fetchNeighborhoodSuggestionCandidates,
  summarizeNeighborhoodSuggestions,
} from '@/utils/deliveryZoneSuggestions';

const EMPTY_ZONE_FORM = {
  neighborhood: '',
  fee: '',
  min_order: '',
  is_active: true,
  source: 'manual',
};

const EMPTY_BATCH_EDIT = {
  fee: '',
  min_order: '',
};

const EMPTY_BULK_CREATE = {
  text: '',
  fee: '',
  min_order: '',
  is_active: true,
};

const EMPTY_SIMULATOR = {
  neighborhood: '',
  subtotal: '',
  latitude: '',
  longitude: '',
};

const EMPTY_AUTOMATION_DEFAULTS = {
  radius_km: '6',
  fee: '',
  min_order: '',
  is_active: true,
  notes: '',
};

const EMPTY_AUTOMATION_RESULT = {
  ready: false,
  origin: null,
  message: '',
  sampledPoints: 0,
  generatedAt: null,
};

function formatCurrency(value) {
  return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value || 0);
}

function formatSourceLabel(source) {
  switch (normalizeZoneSource(source, 'manual')) {
    case 'bulk':
      return 'Lote';
    case 'auto_generated':
      return 'Auto';
    default:
      return 'Manual';
  }
}

function formatRuleSource(source) {
  const map = {
    zone: 'Zona',
    distance: 'Distancia',
    hybrid_zone: 'Hibrido pela zona',
    hybrid_distance: 'Hibrido pela distancia',
    outside_area_blocked: 'Bloqueio fora da area',
    hybrid_outside_area_blocked: 'Hibrido bloqueado',
    fallback_store_fee: 'Taxa padrao da loja',
    hybrid_fallback_store_fee: 'Hibrido com taxa da loja',
    manual_review: 'Revisao manual',
    hybrid_manual_review: 'Hibrido em revisao',
    distance_fallback_zone: 'Zona fallback',
    distance_fallback_store_fee: 'Loja fallback',
    pending_zone_match: 'Aguardando bairro',
    pending_hybrid_resolution: 'Aguardando resolucao hibrida',
  };

  return map[source] || source || 'n/a';
}

function formatPricingModeLabel(mode) {
  switch (mode) {
    case 'distance':
      return 'Modo distancia';
    case 'hybrid':
      return 'Modo hibrido';
    case 'zone':
    default:
      return 'Modo bairro';
  }
}

function formatHybridStrategyLabel(strategy) {
  if (!strategy) return 'n/a';
  switch (strategy) {
    case 'zone_only':
      return 'Zona apenas';
    case 'zone_then_block':
      return 'Zona e bloqueio';
    case 'zone_then_store_fee':
      return 'Zona e taxa da loja';
    case 'zone_then_distance':
    default:
      return 'Zona e depois distancia';
  }
}

function formatDecisionPathStep(step) {
  const map = {
    'zone:matched': 'Zona encontrada',
    'zone:no_active_zone': 'Zona nao encontrada',
    'zone:missing_neighborhood': 'Bairro ausente',
    'distance:calculated': 'Distancia calculada',
    'distance:missing_customer_coordinates': 'Sem coordenadas do cliente',
    'distance:missing_store_coordinates': 'Sem coordenadas da loja',
    'distance:missing_coordinates': 'Sem coordenadas para distancia',
    'distance:unavailable': 'Distancia indisponivel',
    'fallback:block': 'Fallback com bloqueio',
    'fallback:manual_review': 'Fallback com revisao manual',
    'fallback:store_fee': 'Fallback com taxa da loja',
    'strategy:zone_only': 'Estrategia zona apenas',
    'strategy:zone_then_block': 'Estrategia zona e bloqueio',
    'strategy:zone_then_store_fee': 'Estrategia zona e taxa da loja',
  };

  return map[step] || step || 'n/a';
}

function formatSuggestionStatusLabel(status) {
  switch (status) {
    case 'already_registered':
      return 'Ja cadastrado';
    case 'probable_duplicate':
      return 'Duplicado provavel';
    case 'new':
    default:
      return 'Novo';
  }
}

function formatSuggestionSourceLabel(source) {
  switch (source) {
    case 'nominatim_reverse_sample':
      return 'Amostragem regional';
    default:
      return source || 'n/a';
  }
}

function formatSuggestionOriginLabel(origin) {
  switch (origin) {
    case 'store_coordinates':
      return 'Coordenadas da loja';
    case 'store_address_geocode':
      return 'Endereco da loja';
    case 'demo_context_fallback':
      return 'Contexto local';
    default:
      return origin || 'n/a';
  }
}

function formatConfidenceLabel(confidence) {
  switch (confidence) {
    case 'high':
      return 'Alta';
    case 'medium':
      return 'Media';
    case 'low':
      return 'Baixa';
    default:
      return 'n/a';
  }
}

function sortZones(zones, sortBy) {
  const items = [...zones];

  items.sort((left, right) => {
    switch (sortBy) {
      case 'name_desc':
        return left.neighborhood.localeCompare(right.neighborhood, 'pt-BR') * -1;
      case 'fee_desc':
        return Number(right.fee || 0) - Number(left.fee || 0);
      case 'fee_asc':
        return Number(left.fee || 0) - Number(right.fee || 0);
      case 'min_order_desc':
        return Number(right.min_order || 0) - Number(left.min_order || 0);
      case 'status':
        if (left.is_active === right.is_active) {
          return left.neighborhood.localeCompare(right.neighborhood, 'pt-BR');
        }
        return left.is_active ? -1 : 1;
      case 'source':
        return formatSourceLabel(left.source).localeCompare(formatSourceLabel(right.source), 'pt-BR');
      case 'name_asc':
      default:
        return left.neighborhood.localeCompare(right.neighborhood, 'pt-BR');
    }
  });

  return items;
}

export default function DeliveryZonesTab() {
  const [showModal, setShowModal] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterStatus, setFilterStatus] = useState('all');
  const [sourceFilter, setSourceFilter] = useState('all');
  const [sortBy, setSortBy] = useState('name_asc');
  const [formData, setFormData] = useState(EMPTY_ZONE_FORM);
  const [selectedZoneIds, setSelectedZoneIds] = useState([]);
  const [batchEdit, setBatchEdit] = useState(EMPTY_BATCH_EDIT);
  const [bulkCreate, setBulkCreate] = useState(EMPTY_BULK_CREATE);
  const [simulator, setSimulator] = useState(EMPTY_SIMULATOR);
  const [automationDefaults, setAutomationDefaults] = useState(EMPTY_AUTOMATION_DEFAULTS);
  const [automationResult, setAutomationResult] = useState(EMPTY_AUTOMATION_RESULT);
  const [automationCandidates, setAutomationCandidates] = useState([]);
  const [selectedSuggestionIds, setSelectedSuggestionIds] = useState([]);
  const [deliveryConfig, setDeliveryConfig] = useState({
    delivery_fee_mode: 'zone',
    delivery_pricing_mode: 'zone',
    delivery_fee: 0,
    min_order_value: 0,
    latitude: null,
    longitude: null,
    delivery_base_fee: 0,
    delivery_price_per_km: 0,
    delivery_min_fee: 0,
    delivery_max_fee: null,
    delivery_free_distance: null,
    delivery_hybrid_strategy: 'zone_then_distance',
    checkout_address_mode: 'map_optional',
    delivery_outside_area_behavior: 'block',
  });

  const queryClient = useQueryClient();
  const { menuContext } = usePermission();
  const entityOpts = getMenuContextEntityOpts(menuContext);
  const deliveryZonesQueryKey = ['deliveryZones', ...getMenuContextQueryKeyParts(menuContext)];
  const storeQueryKey = ['store', ...getMenuContextQueryKeyParts(menuContext)];

  const scopedCreatePayload = (payload) => ({
    ...payload,
    ...(entityOpts?.as_subscriber_id != null ? { as_subscriber_id: entityOpts.as_subscriber_id } : {}),
    ...(entityOpts?.as_subscriber ? { as_subscriber: entityOpts.as_subscriber } : {}),
  });

  const buildStorePayload = (rawConfig) => {
    const deliveryMode = resolveDeliveryPricingMode(rawConfig);
    const hybridStrategy = resolveDeliveryHybridStrategy({
      ...rawConfig,
      delivery_fee_mode: deliveryMode,
      delivery_pricing_mode: deliveryMode,
    });
    const checkoutAddressMode =
      deliveryMode === 'distance'
        ? 'map_required'
        : resolveCheckoutAddressMode(rawConfig);

    return {
      ...rawConfig,
      delivery_fee_mode: deliveryMode,
      delivery_pricing_mode: deliveryMode,
      delivery_hybrid_strategy: deliveryMode === 'hybrid'
        ? hybridStrategy
        : rawConfig?.delivery_hybrid_strategy || null,
      checkout_address_mode: checkoutAddressMode,
      delivery_outside_area_behavior: resolveOutsideAreaBehavior({
        ...rawConfig,
        delivery_fee_mode: deliveryMode,
        delivery_pricing_mode: deliveryMode,
      }),
    };
  };

  const { data: stores = [] } = useQuery({
    queryKey: storeQueryKey,
    queryFn: async () => {
      if (!menuContext) return [];
      return base44.entities.Store.list(null, getMenuContextEntityOpts(menuContext));
    },
    enabled: !!menuContext,
  });
  const store = stores[0];

  useEffect(() => {
    if (!store) return;
    const deliveryMode = resolveDeliveryPricingMode(store);
    setDeliveryConfig({
      delivery_fee_mode: deliveryMode,
      delivery_pricing_mode: deliveryMode,
      delivery_fee: store.delivery_fee || 0,
      min_order_value: store.min_order_value || store.min_order_price || 0,
      latitude: store.latitude || null,
      longitude: store.longitude || null,
      delivery_base_fee: store.delivery_base_fee || 0,
      delivery_price_per_km: store.delivery_price_per_km || 0,
      delivery_min_fee: store.delivery_min_fee || 0,
      delivery_max_fee: store.delivery_max_fee ?? null,
      delivery_free_distance: store.delivery_free_distance ?? null,
      delivery_hybrid_strategy: resolveDeliveryHybridStrategy(store),
      checkout_address_mode: resolveCheckoutAddressMode(store),
      delivery_outside_area_behavior: resolveOutsideAreaBehavior(store),
    });
  }, [store]);

  const updateStoreMutation = useMutation({
    mutationFn: ({ data }) => base44.entities.Store.update(store.id, buildStorePayload(data), entityOpts),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: storeQueryKey });
      toast.success('Configuracao de entrega salva.');
    },
    onError: (error) => toast.error(error?.message || 'Erro ao salvar configuracao.'),
  });

  const { data: zones = [] } = useQuery({
    queryKey: deliveryZonesQueryKey,
    queryFn: async () => {
      if (!menuContext) return [];
      try {
        const result = await base44.entities.DeliveryZone.list('neighborhood', getMenuContextEntityOpts(menuContext));
        return Array.isArray(result) ? result : [];
      } catch (error) {
        console.error('Erro ao buscar zonas:', error);
        return [];
      }
    },
    enabled: !!menuContext,
    initialData: [],
    refetchOnMount: 'always',
  });

  const normalizedZones = useMemo(() => {
    if (!Array.isArray(zones)) return [];

    return zones
      .map((zone) => buildDeliveryZonePayload(zone, {
        defaultSource: normalizeZoneSource(zone?.source, 'manual'),
      }))
      .filter(Boolean);
  }, [zones]);

  const duplicateGroups = useMemo(() => findDuplicateZoneGroups(normalizedZones), [normalizedZones]);
  const duplicateIdSet = useMemo(() => {
    const ids = new Set();
    duplicateGroups.forEach((group) => {
      group.zones.forEach((zone) => {
        ids.add(String(zone.id || `${group.normalizedNeighborhood}:${zone.neighborhood}`));
      });
    });
    return ids;
  }, [duplicateGroups]);

  const filteredZones = useMemo(() => {
    const normalizedSearch = normalizeNeighborhood(searchTerm);

    const filtered = normalizedZones.filter((zone) => {
      const zoneKey = String(zone.id || `${normalizeNeighborhood(zone.neighborhood)}:${zone.neighborhood}`);
      const matchesSearch =
        !normalizedSearch ||
        normalizeNeighborhood(zone.neighborhood).includes(normalizedSearch) ||
        formatSourceLabel(zone.source).toLowerCase().includes(normalizedSearch);

      const matchesStatus =
        filterStatus === 'all' ||
        (filterStatus === 'active' && zone.is_active) ||
        (filterStatus === 'inactive' && !zone.is_active) ||
        (filterStatus === 'duplicates' && duplicateIdSet.has(zoneKey));

      const matchesSource =
        sourceFilter === 'all' ||
        normalizeZoneSource(zone.source, 'manual') === sourceFilter;

      return matchesSearch && matchesStatus && matchesSource;
    });

    return sortZones(filtered, sortBy);
  }, [duplicateIdSet, filterStatus, normalizedZones, searchTerm, sortBy, sourceFilter]);

  const visibleZoneIds = useMemo(() => (
    filteredZones
      .map((zone) => zone?.id)
      .filter((id) => id !== null && id !== undefined)
      .map((id) => String(id))
  ), [filteredZones]);

  useEffect(() => {
    const availableIds = new Set(normalizedZones.map((zone) => String(zone.id)));
    setSelectedZoneIds((current) => current.filter((id) => availableIds.has(String(id))));
  }, [normalizedZones]);

  const selectedIdSet = useMemo(() => new Set(selectedZoneIds.map((id) => String(id))), [selectedZoneIds]);
  const selectedZones = useMemo(() => (
    normalizedZones.filter((zone) => selectedIdSet.has(String(zone.id)))
  ), [normalizedZones, selectedIdSet]);

  const allVisibleSelected = visibleZoneIds.length > 0 && visibleZoneIds.every((id) => selectedIdSet.has(id));
  const coveredNeighborhoods = useMemo(() => {
    const covered = new Set();
    normalizedZones.forEach((zone) => {
      if (!zone.is_active) return;
      const normalizedName = normalizeNeighborhood(zone.neighborhood);
      if (normalizedName) covered.add(normalizedName);
    });
    return covered.size;
  }, [normalizedZones]);

  const stats = useMemo(() => {
    const active = normalizedZones.filter((zone) => zone.is_active).length;
    const inactive = normalizedZones.filter((zone) => !zone.is_active).length;

    return {
      total: normalizedZones.length,
      active,
      inactive,
      coveredNeighborhoods,
      duplicateGroups: duplicateGroups.length,
    };
  }, [coveredNeighborhoods, duplicateGroups.length, normalizedZones]);

  const bulkPreview = useMemo(() => {
    const parsed = parseBulkZonesInput(bulkCreate.text, {
      fee: bulkCreate.fee,
      minOrder: bulkCreate.min_order,
      isActive: bulkCreate.is_active,
      source: 'bulk',
    });

    const itemsWithConflicts = parsed.items.map((item) => ({
      ...item,
      conflicts: findEquivalentDeliveryZones(normalizedZones, item.neighborhood),
    }));

    return {
      ...parsed,
      itemsWithConflicts,
      validItems: itemsWithConflicts.filter((item) => item.conflicts.length === 0),
      existingConflicts: itemsWithConflicts.filter((item) => item.conflicts.length > 0),
    };
  }, [bulkCreate.fee, bulkCreate.is_active, bulkCreate.min_order, bulkCreate.text, normalizedZones]);

  const simulation = useMemo(() => simulateDeliveryCoverage({
    neighborhood: simulator.neighborhood,
    subtotal: simulator.subtotal,
    deliveryZones: normalizedZones,
    store,
    customerLat: simulator.latitude,
    customerLng: simulator.longitude,
  }), [normalizedZones, simulator.latitude, simulator.longitude, simulator.neighborhood, simulator.subtotal, store]);

  const automationSuggestions = useMemo(() => (
    classifyNeighborhoodSuggestions(automationCandidates, normalizedZones)
  ), [automationCandidates, normalizedZones]);

  const automationSummary = useMemo(() => (
    summarizeNeighborhoodSuggestions(automationSuggestions)
  ), [automationSuggestions]);

  const selectedSuggestionIdSet = useMemo(() => (
    new Set(selectedSuggestionIds.map((id) => String(id)))
  ), [selectedSuggestionIds]);

  const selectedAutomationSuggestions = useMemo(() => (
    automationSuggestions.filter((suggestion) => (
      suggestion.selectable && selectedSuggestionIdSet.has(String(suggestion.id))
    ))
  ), [automationSuggestions, selectedSuggestionIdSet]);

  useEffect(() => {
    const availableIds = new Set(
      automationSuggestions
        .filter((suggestion) => suggestion.selectable)
        .map((suggestion) => String(suggestion.id))
    );

    setSelectedSuggestionIds((current) => current.filter((id) => availableIds.has(String(id))));
  }, [automationSuggestions]);

  const closeModal = () => {
    setShowModal(false);
    setFormData(EMPTY_ZONE_FORM);
  };

  const createMutation = useMutation({
    mutationFn: (data) => base44.entities.DeliveryZone.create(scopedCreatePayload(
      buildDeliveryZonePayload(data, { defaultSource: 'manual' })
    )),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: deliveryZonesQueryKey });
      closeModal();
      toast.success('Zona criada com sucesso.');
    },
    onError: (error) => toast.error(error?.message || 'Erro ao criar zona.'),
  });

  const bulkCreateMutation = useMutation({
    mutationFn: async ({ items }) => {
      await Promise.all(items.map((item) => base44.entities.DeliveryZone.create(scopedCreatePayload(
        buildDeliveryZonePayload(item, { defaultSource: 'bulk' })
      ))));

      return items.length;
    },
    onSuccess: (createdCount) => {
      queryClient.invalidateQueries({ queryKey: deliveryZonesQueryKey });
      setBulkCreate(EMPTY_BULK_CREATE);
      toast.success(`${createdCount} zonas criadas em lote.`);
    },
    onError: (error) => toast.error(error?.message || 'Erro no cadastro em lote.'),
  });

  const automationSuggestMutation = useMutation({
    mutationFn: async () => fetchNeighborhoodSuggestionCandidates({
      store,
      radiusKm: automationDefaults.radius_km,
      fetchImpl: fetch,
    }),
    onSuccess: (result) => {
      const generatedAt = new Date().toISOString();
      const classified = classifyNeighborhoodSuggestions(result?.suggestions || [], normalizedZones);

      setAutomationCandidates(result?.suggestions || []);
      setAutomationResult({
        ready: result?.ready === true,
        origin: result?.origin || null,
        message: result?.message || result?.origin?.message || '',
        sampledPoints: result?.sampledPoints || 0,
        generatedAt,
      });
      setSelectedSuggestionIds(
        classified
          .filter((suggestion) => suggestion.selectable)
          .map((suggestion) => String(suggestion.id))
      );

      if (!result?.ready) {
        toast.error(result?.origin?.message || result?.message || 'Nao foi possivel preparar sugestoes de bairros.');
        return;
      }

      if ((result?.suggestions || []).length === 0) {
        toast('Nenhum bairro novo foi sugerido com confianca ao redor da loja.');
        return;
      }

      const summary = summarizeNeighborhoodSuggestions(classified);
      toast.success(
        `${summary.total} sugestoes carregadas: ${summary.new} novas, ${summary.already_registered} ja cadastradas e ${summary.probable_duplicate} em revisao.`
      );
    },
    onError: (error) => {
      setAutomationResult({
        ...EMPTY_AUTOMATION_RESULT,
        message: error?.message || 'Erro ao buscar bairros da regiao.',
      });
      toast.error(error?.message || 'Erro ao buscar bairros da regiao.');
    },
  });

  const automationCreateMutation = useMutation({
    mutationFn: async ({ items }) => {
      await Promise.all(items.map((item) => base44.entities.DeliveryZone.create(scopedCreatePayload(item))));
      return items.length;
    },
    onSuccess: (count) => {
      queryClient.invalidateQueries({ queryKey: deliveryZonesQueryKey });
      setSelectedSuggestionIds([]);
      toast.success(`${count} bairros sugeridos criados como auto_generated.`);
    },
    onError: (error) => toast.error(error?.message || 'Erro ao criar bairros sugeridos.'),
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }) => base44.entities.DeliveryZone.update(
      id,
      buildDeliveryZonePayload(data, {
        defaultSource: normalizeZoneSource(data?.source, 'manual'),
      }),
      entityOpts
    ),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: deliveryZonesQueryKey });
      toast.success(variables?.successMessage || 'Zona atualizada.');
    },
    onError: (error) => toast.error(error?.message || 'Erro ao atualizar zona.'),
  });

  const batchUpdateMutation = useMutation({
    mutationFn: async ({ zonesToUpdate, updater, successMessage }) => {
      await Promise.all(zonesToUpdate.map((zone) => base44.entities.DeliveryZone.update(
        zone.id,
        buildDeliveryZonePayload(updater(zone), {
          defaultSource: normalizeZoneSource(zone?.source, 'manual'),
        }),
        entityOpts
      )));

      return {
        count: zonesToUpdate.length,
        successMessage,
      };
    },
    onSuccess: (result) => {
      queryClient.invalidateQueries({ queryKey: deliveryZonesQueryKey });
      setSelectedZoneIds([]);
      setBatchEdit(EMPTY_BATCH_EDIT);
      toast.success(result?.successMessage || `${result?.count || 0} zonas atualizadas.`);
    },
    onError: (error) => toast.error(error?.message || 'Erro na acao em lote.'),
  });

  const deleteMutation = useMutation({
    mutationFn: (id) => base44.entities.DeliveryZone.delete(id, entityOpts),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: deliveryZonesQueryKey });
      toast.success('Zona excluida.');
    },
    onError: (error) => toast.error(error?.message || 'Erro ao excluir zona.'),
  });

  const batchDeleteMutation = useMutation({
    mutationFn: async ({ ids }) => {
      await Promise.all(ids.map((id) => base44.entities.DeliveryZone.delete(id, entityOpts)));
      return ids.length;
    },
    onSuccess: (count) => {
      queryClient.invalidateQueries({ queryKey: deliveryZonesQueryKey });
      setSelectedZoneIds([]);
      toast.success(`${count} zonas excluidas.`);
    },
    onError: (error) => toast.error(error?.message || 'Erro ao excluir zonas em lote.'),
  });

  const handleSingleCreate = (event) => {
    event.preventDefault();
    const conflicts = findEquivalentDeliveryZones(normalizedZones, formData.neighborhood);

    if (conflicts.length > 0) {
      toast.error(`Ja existe uma zona equivalente para "${conflicts[0].neighborhood}".`);
      return;
    }

    createMutation.mutate({
      ...formData,
      source: 'manual',
    });
  };

  const handleBulkCreate = () => {
    if (bulkPreview.validItems.length === 0) {
      toast.error('Nao ha zonas validas para criar em lote.');
      return;
    }

    bulkCreateMutation.mutate({ items: bulkPreview.validItems });
  };

  const handleAutomationSearch = () => {
    if (!store) {
      toast.error('Loja nao encontrada para sugerir bairros.');
      return;
    }

    automationSuggestMutation.mutate();
  };

  const toggleSuggestionSelection = (id, checked) => {
    const normalizedId = String(id);

    setSelectedSuggestionIds((current) => {
      const next = new Set(current.map((value) => String(value)));
      if (checked === true) {
        next.add(normalizedId);
      } else {
        next.delete(normalizedId);
      }
      return Array.from(next);
    });
  };

  const selectAllNewSuggestions = () => {
    setSelectedSuggestionIds(
      automationSuggestions
        .filter((suggestion) => suggestion.selectable)
        .map((suggestion) => String(suggestion.id))
    );
  };

  const clearAutomationPreview = () => {
    setAutomationCandidates([]);
    setSelectedSuggestionIds([]);
    setAutomationResult(EMPTY_AUTOMATION_RESULT);
  };

  const handleCreateAutoGeneratedZones = () => {
    const items = buildAutoGeneratedZonePayloads({
      suggestions: automationSuggestions,
      selectedIds: selectedSuggestionIds,
      defaults: {
        fee: automationDefaults.fee,
        min_order: automationDefaults.min_order,
        is_active: automationDefaults.is_active,
        notes: automationDefaults.notes,
        generatedAt: automationResult.generatedAt || new Date().toISOString(),
      },
    });

    if (items.length === 0) {
      toast.error('Selecione ao menos uma sugestao nova para criar.');
      return;
    }

    automationCreateMutation.mutate({ items });
  };

  const toggleZoneSelection = (id, checked) => {
    const normalizedId = String(id);
    setSelectedZoneIds((current) => {
      const next = new Set(current.map((value) => String(value)));
      if (checked === true) {
        next.add(normalizedId);
      } else {
        next.delete(normalizedId);
      }
      return Array.from(next);
    });
  };

  const toggleAllVisible = (checked) => {
    setSelectedZoneIds((current) => {
      const next = new Set(current.map((value) => String(value)));
      visibleZoneIds.forEach((id) => {
        if (checked === true) {
          next.add(String(id));
        } else {
          next.delete(String(id));
        }
      });
      return Array.from(next);
    });
  };

  const applyBatchStatus = (isActive) => {
    if (selectedZones.length === 0) {
      toast.error('Selecione ao menos uma zona.');
      return;
    }

    batchUpdateMutation.mutate({
      zonesToUpdate: selectedZones,
      updater: (zone) => ({ ...zone, is_active: isActive }),
      successMessage: isActive
        ? `${selectedZones.length} zonas ativadas.`
        : `${selectedZones.length} zonas desativadas.`,
    });
  };

  const applyBatchValues = () => {
    if (selectedZones.length === 0) {
      toast.error('Selecione ao menos uma zona.');
      return;
    }

    const hasFee = batchEdit.fee !== '';
    const hasMinOrder = batchEdit.min_order !== '';

    if (!hasFee && !hasMinOrder) {
      toast.error('Informe ao menos uma taxa ou pedido minimo para aplicar.');
      return;
    }

    batchUpdateMutation.mutate({
      zonesToUpdate: selectedZones,
      updater: (zone) => ({
        ...zone,
        ...(hasFee ? { fee: batchEdit.fee } : {}),
        ...(hasMinOrder ? { min_order: batchEdit.min_order } : {}),
      }),
      successMessage: `${selectedZones.length} zonas atualizadas em lote.`,
    });
  };

  const deleteSelected = () => {
    if (selectedZones.length === 0) {
      toast.error('Selecione ao menos uma zona.');
      return;
    }

    if (!window.confirm(`Excluir ${selectedZones.length} zonas selecionadas?`)) {
      return;
    }

    batchDeleteMutation.mutate({
      ids: selectedZones.map((zone) => zone.id),
    });
  };

  const handleNeighborhoodBlur = (zone, rawValue, inputElement) => {
    const nextNeighborhood = String(rawValue || '').replace(/\s+/g, ' ').trim();

    if (!nextNeighborhood) {
      inputElement.value = zone.neighborhood;
      toast.error('O bairro nao pode ficar vazio.');
      return;
    }

    if (nextNeighborhood === zone.neighborhood) return;

    const conflicts = findEquivalentDeliveryZones(normalizedZones, nextNeighborhood, { ignoreId: zone.id });
    if (conflicts.length > 0) {
      inputElement.value = zone.neighborhood;
      toast.error(`Ja existe uma zona equivalente para "${conflicts[0].neighborhood}".`);
      return;
    }

    updateMutation.mutate({
      id: zone.id,
      data: { ...zone, neighborhood: nextNeighborhood, name: nextNeighborhood },
      successMessage: 'Bairro atualizado.',
    });
  };

  const handleNumericBlur = (zone, field, rawValue, inputElement, options = {}) => {
    const nullable = options.nullable === true;
    const currentValue = nullable ? zone[field] ?? '' : Number(zone[field] || 0);
    const trimmed = String(rawValue || '').trim();

    if (trimmed === '') {
      if (!nullable) {
        inputElement.value = String(zone[field] ?? 0);
        return;
      }

      if (zone[field] == null) return;
      updateMutation.mutate({
        id: zone.id,
        data: { ...zone, [field]: null },
        successMessage: 'Zona atualizada.',
      });
      return;
    }

    const parsed = Number(trimmed.replace(',', '.'));
    if (!Number.isFinite(parsed)) {
      inputElement.value = String(currentValue);
      toast.error('Informe um numero valido.');
      return;
    }

    const nextValue = Math.round((parsed + Number.EPSILON) * 100) / 100;
    if (Number(currentValue || 0) === nextValue) return;

    updateMutation.mutate({
      id: zone.id,
      data: { ...zone, [field]: nextValue },
      successMessage: 'Zona atualizada.',
    });
  };

  return (
    <div className="p-4 sm:p-6 space-y-6">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div className="space-y-1">
          <h2 className="text-2xl font-bold">Zona de Entrega</h2>
          <p className="text-sm text-muted-foreground">
            Operacao por bairro, distancia e modo hibrido com a mesma regra de frete do checkout e do pedido final.
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <Badge variant="outline">{formatPricingModeLabel(resolveDeliveryPricingMode(store))}</Badge>
          <Badge variant={duplicateGroups.length > 0 ? 'destructive' : 'secondary'}>
            {duplicateGroups.length > 0 ? `${duplicateGroups.length} conflitos` : 'Sem conflitos ativos'}
          </Badge>
          <Button onClick={() => setShowModal(true)} className="bg-orange-500 hover:bg-orange-600">
            <Plus className="w-4 h-4 mr-2" />
            Nova Zona
          </Button>
        </div>
      </div>

      {store && (
        <Card>
          <CardHeader>
            <CardTitle>Configuracao de entrega</CardTitle>
            <CardDescription>
              Ajuste o modo de calculo e o comportamento padrao antes de operar as zonas.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label className="mb-2 block">Modo de calculo</Label>
              <div className="flex gap-2">
                <Button
                  type="button"
                  variant={deliveryConfig.delivery_fee_mode === 'zone' ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setDeliveryConfig((current) => ({
                    ...current,
                    delivery_fee_mode: 'zone',
                    delivery_pricing_mode: 'zone',
                  }))}
                >
                  Por zona/bairro
                </Button>
                <Button
                  type="button"
                  variant={deliveryConfig.delivery_fee_mode === 'hybrid' ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setDeliveryConfig((current) => ({
                    ...current,
                    delivery_fee_mode: 'hybrid',
                    delivery_pricing_mode: 'hybrid',
                    delivery_hybrid_strategy: current.delivery_hybrid_strategy || 'zone_then_distance',
                  }))}
                >
                  Hibrido forte
                </Button>
                <Button
                  type="button"
                  variant={deliveryConfig.delivery_fee_mode === 'distance' ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setDeliveryConfig((current) => ({
                    ...current,
                    delivery_fee_mode: 'distance',
                    delivery_pricing_mode: 'distance',
                    checkout_address_mode: 'map_required',
                  }))}
                >
                  Por distancia (km)
                </Button>
              </div>
            </div>
            {deliveryConfig.delivery_fee_mode === 'hybrid' && (
              <div>
                <Label className="mb-2 block">Estrategia hibrida</Label>
                <Select
                  value={deliveryConfig.delivery_hybrid_strategy}
                  onValueChange={(value) => setDeliveryConfig((current) => ({ ...current, delivery_hybrid_strategy: value }))}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="zone_then_distance">Zona e depois distancia</SelectItem>
                    <SelectItem value="zone_only">Zona apenas</SelectItem>
                    <SelectItem value="zone_then_block">Zona e depois bloquear</SelectItem>
                    <SelectItem value="zone_then_store_fee">Zona e depois taxa da loja</SelectItem>
                  </SelectContent>
                </Select>
                <p className="text-xs text-muted-foreground mt-2">
                  No hibrido, o sistema sempre tenta bairro primeiro e so depois segue para a estrategia configurada.
                </p>
              </div>
            )}
            <div>
              <Label className="mb-2 block">Endereco no checkout</Label>
              <Select
                value={deliveryConfig.delivery_fee_mode === 'distance' ? 'map_required' : deliveryConfig.checkout_address_mode}
                onValueChange={(value) => setDeliveryConfig((current) => ({ ...current, checkout_address_mode: value }))}
                disabled={deliveryConfig.delivery_fee_mode === 'distance'}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="text_only">So texto</SelectItem>
                  <SelectItem value="map_optional">Mapa opcional</SelectItem>
                  <SelectItem value="map_required">Mapa obrigatorio</SelectItem>
                </SelectContent>
              </Select>
              <p className="text-xs text-muted-foreground mt-2">
                {deliveryConfig.delivery_fee_mode === 'distance'
                  ? 'No modo por km, o mapa segue obrigatorio neste lote.'
                  : deliveryConfig.delivery_fee_mode === 'hybrid'
                  ? 'No modo hibrido, o checkout pode resolver pelo bairro e usar distancia quando houver coordenadas.'
                  : 'No modo por bairro, o checkout pode operar so com endereco textual.'}
              </p>
            </div>
            <div>
              <Label className="mb-2 block">Bairro fora da area</Label>
              <Select
                value={deliveryConfig.delivery_outside_area_behavior}
                onValueChange={(value) => setDeliveryConfig((current) => ({ ...current, delivery_outside_area_behavior: value }))}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="block">Bloquear pedido</SelectItem>
                  <SelectItem value="fallback_store_fee">Usar taxa padrao da loja</SelectItem>
                  <SelectItem value="allow_manual_review">Permitir revisao manual</SelectItem>
                </SelectContent>
              </Select>
            </div>
            {(deliveryConfig.delivery_fee_mode === 'zone' || deliveryConfig.delivery_fee_mode === 'hybrid') && (
              <div>
                <Label>Taxa padrao (R$)</Label>
                <Input
                  type="number"
                  step="0.01"
                  value={deliveryConfig.delivery_fee}
                  onChange={(event) => setDeliveryConfig((current) => ({
                    ...current,
                    delivery_fee: parseFloat(event.target.value) || 0,
                  }))}
                />
              </div>
            )}
            {(deliveryConfig.delivery_fee_mode === 'distance' || deliveryConfig.delivery_fee_mode === 'hybrid') && (
              <>
                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <Label>Latitude</Label>
                    <Input
                      type="number"
                      step="0.000001"
                      value={deliveryConfig.latitude || ''}
                      onChange={(event) => setDeliveryConfig((current) => ({
                        ...current,
                        latitude: event.target.value ? parseFloat(event.target.value) : null,
                      }))}
                      placeholder="-2.53"
                    />
                  </div>
                  <div>
                    <Label>Longitude</Label>
                    <Input
                      type="number"
                      step="0.000001"
                      value={deliveryConfig.longitude || ''}
                      onChange={(event) => setDeliveryConfig((current) => ({
                        ...current,
                        longitude: event.target.value ? parseFloat(event.target.value) : null,
                      }))}
                      placeholder="-44.29"
                    />
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <Label>Taxa base (R$)</Label>
                    <Input
                      type="number"
                      step="0.01"
                      value={deliveryConfig.delivery_base_fee}
                      onChange={(event) => setDeliveryConfig((current) => ({
                        ...current,
                        delivery_base_fee: parseFloat(event.target.value) || 0,
                      }))}
                    />
                  </div>
                  <div>
                    <Label>R$ por km</Label>
                    <Input
                      type="number"
                      step="0.01"
                      value={deliveryConfig.delivery_price_per_km}
                      onChange={(event) => setDeliveryConfig((current) => ({
                        ...current,
                        delivery_price_per_km: parseFloat(event.target.value) || 0,
                      }))}
                    />
                  </div>
                </div>
                <div className="grid grid-cols-3 gap-2">
                  <div>
                    <Label>Taxa min (R$)</Label>
                    <Input
                      type="number"
                      step="0.01"
                      value={deliveryConfig.delivery_min_fee}
                      onChange={(event) => setDeliveryConfig((current) => ({
                        ...current,
                        delivery_min_fee: parseFloat(event.target.value) || 0,
                      }))}
                    />
                  </div>
                  <div>
                    <Label>Taxa max (R$)</Label>
                    <Input
                      type="number"
                      step="0.01"
                      value={deliveryConfig.delivery_max_fee ?? ''}
                      onChange={(event) => setDeliveryConfig((current) => ({
                        ...current,
                        delivery_max_fee: event.target.value ? parseFloat(event.target.value) : null,
                      }))}
                    />
                  </div>
                  <div>
                    <Label>Gratis ate (km)</Label>
                    <Input
                      type="number"
                      step="0.1"
                      value={deliveryConfig.delivery_free_distance ?? ''}
                      onChange={(event) => setDeliveryConfig((current) => ({
                        ...current,
                        delivery_free_distance: event.target.value ? parseFloat(event.target.value) : null,
                      }))}
                    />
                  </div>
                </div>
              </>
            )}
            <div>
              <Label>Pedido minimo (R$)</Label>
              <Input
                type="number"
                step="0.01"
                value={deliveryConfig.min_order_value}
                onChange={(event) => setDeliveryConfig((current) => ({
                  ...current,
                  min_order_value: parseFloat(event.target.value) || 0,
                }))}
              />
            </div>
            <Button
              onClick={() => updateStoreMutation.mutate({ data: buildStorePayload(deliveryConfig) })}
              disabled={updateStoreMutation.isPending}
            >
              Salvar configuracao
            </Button>
          </CardContent>
        </Card>
      )}

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Total de zonas</p>
                <p className="text-2xl font-bold">{stats.total}</p>
              </div>
              <Layers3 className="w-8 h-8 text-blue-500" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Ativas</p>
                <p className="text-2xl font-bold text-green-600">{stats.active}</p>
              </div>
              <TrendingUp className="w-8 h-8 text-green-500" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Inativas</p>
                <p className="text-2xl font-bold text-muted-foreground">{stats.inactive}</p>
              </div>
              <Package className="w-8 h-8 text-muted-foreground" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Bairros cobertos</p>
                <p className="text-2xl font-bold text-orange-600">{stats.coveredNeighborhoods}</p>
              </div>
              <MapPin className="w-8 h-8 text-orange-500" />
            </div>
          </CardContent>
        </Card>
      </div>

      {duplicateGroups.length > 0 && (
        <Card className="border-amber-300 bg-amber-50/60">
          <CardContent className="p-4 space-y-3">
            <div className="flex items-start gap-3">
              <ShieldAlert className="w-5 h-5 text-amber-600 mt-0.5" />
              <div>
                <p className="font-semibold text-amber-900">Conflitos de cobertura detectados</p>
                <p className="text-sm text-amber-800">
                  Existem {duplicateGroups.length} grupos de bairros equivalentes que podem gerar operacao confusa no admin.
                </p>
              </div>
            </div>
            <div className="flex flex-wrap gap-2">
              {duplicateGroups.slice(0, 4).map((group) => (
                <Badge key={group.normalizedNeighborhood} variant="outline" className="border-amber-400 text-amber-900">
                  {group.labels.join(' / ')}
                </Badge>
              ))}
              {duplicateGroups.length > 4 && (
                <Badge variant="outline" className="border-amber-400 text-amber-900">
                  +{duplicateGroups.length - 4} conflitos
                </Badge>
              )}
            </div>
          </CardContent>
        </Card>
      )}

      <div className="grid gap-6 xl:grid-cols-[1.15fr_1fr]">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Upload className="w-5 h-5" />
              Cadastro em lote
            </CardTitle>
            <CardDescription>
              Cole uma lista de bairros. Formato opcional por linha: Bairro; taxa; pedido minimo; ativo/inativo.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid gap-3 md:grid-cols-3">
              <div>
                <Label>Taxa padrao do lote (R$)</Label>
                <Input
                  type="number"
                  step="0.01"
                  value={bulkCreate.fee}
                  onChange={(event) => setBulkCreate((current) => ({ ...current, fee: event.target.value }))}
                  placeholder="0.00"
                />
              </div>
              <div>
                <Label>Pedido minimo padrao (R$)</Label>
                <Input
                  type="number"
                  step="0.01"
                  value={bulkCreate.min_order}
                  onChange={(event) => setBulkCreate((current) => ({ ...current, min_order: event.target.value }))}
                  placeholder="Opcional"
                />
              </div>
              <div className="rounded-lg border px-3 py-2 flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium">Novas zonas ativas</p>
                  <p className="text-xs text-muted-foreground">Padrao para linhas sem status</p>
                </div>
                <Switch
                  checked={bulkCreate.is_active}
                  onCheckedChange={(checked) => setBulkCreate((current) => ({ ...current, is_active: checked === true }))}
                />
              </div>
            </div>
            <Textarea
              value={bulkCreate.text}
              onChange={(event) => setBulkCreate((current) => ({ ...current, text: event.target.value }))}
              placeholder={'Centro\nRenascenca\nAngelim; 9.50; 30; ativo'}
              className="min-h-[220px]"
            />
            <div className="flex flex-wrap gap-2">
              <Badge variant="secondary">{bulkPreview.validItems.length} validas</Badge>
              <Badge variant="outline">{bulkPreview.duplicatesInInput.length} duplicadas na lista</Badge>
              <Badge variant="outline">{bulkPreview.existingConflicts.length} em conflito com existentes</Badge>
              <Badge variant="outline">{bulkPreview.invalidLines.length} invalidas</Badge>
            </div>
            {bulkPreview.existingConflicts.length > 0 && (
              <div className="rounded-lg border border-amber-300 bg-amber-50 p-3">
                <p className="text-sm font-medium text-amber-900">Linhas em conflito com zonas ja existentes</p>
                <p className="text-xs text-amber-800 mt-1">
                  Essas linhas serao ignoradas para evitar duplicata silenciosa.
                </p>
                <div className="flex flex-wrap gap-2 mt-3">
                  {bulkPreview.existingConflicts.slice(0, 6).map((item) => (
                    <Badge key={`${item.lineNumber}:${item.neighborhood}`} variant="outline" className="border-amber-400 text-amber-900">
                      Linha {item.lineNumber}: {item.neighborhood}
                    </Badge>
                  ))}
                </div>
              </div>
            )}
            <Button
              onClick={handleBulkCreate}
              disabled={bulkCreateMutation.isPending || bulkPreview.validItems.length === 0}
            >
              Criar zonas validas
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <TestTube2 className="w-5 h-5" />
              Simular entrega
            </CardTitle>
            <CardDescription>
              Usa a mesma regra central do runtime para explicar cobertura, taxa e motivo da decisao.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label>Bairro</Label>
              <Input
                value={simulator.neighborhood}
                onChange={(event) => setSimulator((current) => ({ ...current, neighborhood: event.target.value }))}
                placeholder="Ex: Renascenca"
              />
            </div>
            <div className="grid gap-3 md:grid-cols-3">
              <div>
                <Label>Subtotal (opcional)</Label>
                <Input
                  type="number"
                  step="0.01"
                  value={simulator.subtotal}
                  onChange={(event) => setSimulator((current) => ({ ...current, subtotal: event.target.value }))}
                  placeholder="0.00"
                />
              </div>
              <div>
                <Label>Latitude (opcional)</Label>
                <Input
                  type="number"
                  step="0.000001"
                  value={simulator.latitude}
                  onChange={(event) => setSimulator((current) => ({ ...current, latitude: event.target.value }))}
                  placeholder="-2.53"
                />
              </div>
              <div>
                <Label>Longitude (opcional)</Label>
                <Input
                  type="number"
                  step="0.000001"
                  value={simulator.longitude}
                  onChange={(event) => setSimulator((current) => ({ ...current, longitude: event.target.value }))}
                  placeholder="-44.29"
                />
              </div>
            </div>
            <div className={`rounded-xl border p-4 ${
              !simulation.ready
                ? 'border-border bg-muted/30'
                : simulation.allowed
                  ? 'border-green-300 bg-green-50/70'
                  : 'border-red-300 bg-red-50/70'
            }`}>
              <div className="flex flex-wrap items-center gap-2">
                <Badge variant={
                  !simulation.ready
                    ? 'outline'
                    : simulation.allowed
                      ? 'secondary'
                      : 'destructive'
                }>
                  {!simulation.ready ? 'Aguardando bairro' : simulation.allowed ? 'Entrega permitida' : 'Entrega bloqueada'}
                </Badge>
                <Badge variant="outline">{formatRuleSource(simulation.deliveryRuleSource)}</Badge>
                <Badge variant="outline">{simulation.deliveryFeeModeApplied || 'n/a'}</Badge>
                {simulation.belowMinimumOrder && (
                  <Badge variant="outline" className="border-amber-400 text-amber-900">
                    Subtotal abaixo do minimo
                  </Badge>
                )}
              </div>
              <p className="text-sm mt-3">{simulation.decisionMessage}</p>
              <div className="grid gap-3 sm:grid-cols-2 mt-4 text-sm">
                <div className="rounded-lg border bg-background/80 p-3">
                  <p className="text-xs text-muted-foreground">Modo aplicado</p>
                  <p className="font-medium">{simulation.deliveryFeeModeApplied || 'n/a'}</p>
                </div>
                <div className="rounded-lg border bg-background/80 p-3">
                  <p className="text-xs text-muted-foreground">Estrategia hibrida</p>
                  <p className="font-medium">{formatHybridStrategyLabel(simulation.hybridStrategy)}</p>
                </div>
                <div className="rounded-lg border bg-background/80 p-3">
                  <p className="text-xs text-muted-foreground">Zona encontrada</p>
                  <p className="font-medium">{simulation.matchedZoneName || 'Nenhuma'}</p>
                </div>
                <div className="rounded-lg border bg-background/80 p-3">
                  <p className="text-xs text-muted-foreground">Taxa aplicada</p>
                  <p className="font-medium">{formatCurrency(simulation.deliveryFee)}</p>
                </div>
                <div className="rounded-lg border bg-background/80 p-3">
                  <p className="text-xs text-muted-foreground">Pedido minimo considerado</p>
                  <p className="font-medium">{formatCurrency(simulation.minimumOrderValue)}</p>
                </div>
                <div className="rounded-lg border bg-background/80 p-3">
                  <p className="text-xs text-muted-foreground">Distancia</p>
                  <p className="font-medium">
                    {simulation.distanceKm == null ? 'n/a' : `${simulation.distanceKm.toFixed(3)} km`}
                  </p>
                </div>
                <div className="rounded-lg border bg-background/80 p-3">
                  <p className="text-xs text-muted-foreground">Motivo</p>
                  <p className="font-medium">{simulation.blockReason || 'ok'}</p>
                </div>
              </div>
              <div className="rounded-lg border bg-background/80 p-3 mt-4">
                <p className="text-xs text-muted-foreground">Caminho da decisao</p>
                <div className="flex flex-wrap gap-2 mt-2">
                  {(simulation.decisionPath || []).length > 0 ? (
                    simulation.decisionPath.map((step) => (
                      <Badge key={step} variant="outline">
                        {formatDecisionPathStep(step)}
                      </Badge>
                    ))
                  ) : (
                    <span className="text-sm text-muted-foreground">n/a</span>
                  )}
                </div>
                <p className="text-sm mt-3">{simulation.decisionSummary || 'n/a'}</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card className="border-dashed">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="w-5 h-5" />
            Sugestao assistida de bairros
          </CardTitle>
          <CardDescription>
            Usa a loja como origem, busca bairros proximos com fonte publica e deixa tudo em preview antes de criar em lote.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-5">
          <div className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]">
            <div className="space-y-4">
              <div className="grid gap-3 md:grid-cols-3">
                <div>
                  <Label>Raio da busca (km)</Label>
                  <Input
                    type="number"
                    min="1"
                    step="1"
                    value={automationDefaults.radius_km}
                    onChange={(event) => setAutomationDefaults((current) => ({ ...current, radius_km: event.target.value }))}
                    placeholder="6"
                  />
                </div>
                <div>
                  <Label>Taxa padrao sugerida (R$)</Label>
                  <Input
                    type="number"
                    step="0.01"
                    value={automationDefaults.fee}
                    onChange={(event) => setAutomationDefaults((current) => ({ ...current, fee: event.target.value }))}
                    placeholder="0.00"
                  />
                </div>
                <div>
                  <Label>Pedido minimo padrao (R$)</Label>
                  <Input
                    type="number"
                    step="0.01"
                    value={automationDefaults.min_order}
                    onChange={(event) => setAutomationDefaults((current) => ({ ...current, min_order: event.target.value }))}
                    placeholder="Opcional"
                  />
                </div>
              </div>

              <div className="rounded-lg border px-3 py-2 flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium">Criar sugestoes como ativas</p>
                  <p className="text-xs text-muted-foreground">Todas as aprovadas saem com source = auto_generated</p>
                </div>
                <Switch
                  checked={automationDefaults.is_active}
                  onCheckedChange={(checked) => setAutomationDefaults((current) => ({ ...current, is_active: checked === true }))}
                />
              </div>

              <div>
                <Label>Observacao padrao (opcional)</Label>
                <Textarea
                  value={automationDefaults.notes}
                  onChange={(event) => setAutomationDefaults((current) => ({ ...current, notes: event.target.value }))}
                  placeholder="Ex: lote sugerido para cobertura inicial da regiao"
                  className="min-h-[96px]"
                />
              </div>

              <div className="flex flex-wrap gap-2">
                <Button
                  type="button"
                  onClick={handleAutomationSearch}
                  disabled={automationSuggestMutation.isPending}
                >
                  Buscar bairros da regiao
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  onClick={selectAllNewSuggestions}
                  disabled={automationSummary.new === 0}
                >
                  Selecionar novos
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  onClick={clearAutomationPreview}
                  disabled={automationCandidates.length === 0 && !automationResult.message}
                >
                  Limpar preview
                </Button>
                <Button
                  type="button"
                  onClick={handleCreateAutoGeneratedZones}
                  disabled={selectedAutomationSuggestions.length === 0 || automationCreateMutation.isPending}
                >
                  Criar selecionadas
                </Button>
              </div>
            </div>

            <div className="rounded-xl border bg-muted/20 p-4 space-y-4">
              <div>
                <p className="text-sm font-medium">Como a busca esta sendo feita</p>
                <p className="text-sm text-muted-foreground mt-1">
                  {automationResult.origin?.label || 'Primeiro tentamos coordenadas da loja, depois endereco textual e, em contexto local, fallback de demo.'}
                </p>
              </div>

              <div className="flex flex-wrap gap-2">
                <Badge variant="secondary">{automationSummary.total} encontradas</Badge>
                <Badge variant="outline">{automationSummary.new} novas</Badge>
                <Badge variant="outline">{automationSummary.already_registered} ja cadastradas</Badge>
                <Badge variant="outline">{automationSummary.probable_duplicate} em conflito</Badge>
              </div>

              {automationResult.origin && (
                <div className="grid gap-3 sm:grid-cols-2 text-sm">
                  <div className="rounded-lg border bg-background/80 p-3">
                    <p className="text-xs text-muted-foreground">Origem aplicada</p>
                    <p className="font-medium">{formatSuggestionOriginLabel(automationResult.origin.source)}</p>
                  </div>
                  <div className="rounded-lg border bg-background/80 p-3">
                    <p className="text-xs text-muted-foreground">Confianca</p>
                    <p className="font-medium">{formatConfidenceLabel(automationResult.origin.confidence)}</p>
                  </div>
                  <div className="rounded-lg border bg-background/80 p-3">
                    <p className="text-xs text-muted-foreground">Pontos amostrados</p>
                    <p className="font-medium">{automationResult.sampledPoints || 0}</p>
                  </div>
                  <div className="rounded-lg border bg-background/80 p-3">
                    <p className="text-xs text-muted-foreground">Cidade/UF base</p>
                    <p className="font-medium">
                      {[automationResult.origin.city, automationResult.origin.state].filter(Boolean).join(' / ') || 'n/a'}
                    </p>
                  </div>
                </div>
              )}

              {(automationResult.message || automationResult.origin?.warning) && (
                <div className="rounded-lg border border-amber-300 bg-amber-50 p-3">
                  <p className="text-sm font-medium text-amber-900">Observacao da automacao</p>
                  <p className="text-xs text-amber-800 mt-1">
                    {automationResult.message || automationResult.origin?.warning}
                  </p>
                </div>
              )}

              <div className="rounded-lg border bg-background/70 p-3">
                <p className="text-xs text-muted-foreground">Aprovacao atual</p>
                <p className="text-sm font-medium mt-1">
                  {selectedAutomationSuggestions.length} bairros novos prontos para criacao em lote.
                </p>
                <p className="text-xs text-muted-foreground mt-1">
                  Sugestoes com conflito ficam visiveis, mas nao entram silenciosamente na criacao.
                </p>
              </div>
            </div>
          </div>

          {automationSuggestions.length === 0 ? (
            <div className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">
              Clique em "Buscar bairros da regiao" para gerar uma lista assistida a partir da loja. O fluxo manual e o lote tradicional continuam funcionando normalmente.
            </div>
          ) : (
            <div className="space-y-3">
              <div className="flex flex-wrap gap-2">
                <Badge variant="outline">Novo</Badge>
                <Badge variant="outline">Ja cadastrado</Badge>
                <Badge variant="outline">Duplicado provavel</Badge>
                <Badge variant="outline">Source final: auto_generated</Badge>
              </div>
              <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                {automationSuggestions.map((suggestion) => {
                  const conflictLabels = suggestion.exactMatches.length > 0
                    ? suggestion.exactMatches.map((item) => item.neighborhood)
                    : suggestion.probableMatches.map((item) => item.neighborhood);

                  const statusTone =
                    suggestion.status === 'new'
                      ? 'border-green-300 bg-green-50/50'
                      : suggestion.status === 'probable_duplicate'
                        ? 'border-amber-300 bg-amber-50/60'
                        : 'border-border bg-muted/30';

                  return (
                    <div key={suggestion.id} className={`rounded-xl border p-4 space-y-3 ${statusTone}`}>
                      <div className="flex items-start gap-3">
                        <Checkbox
                          checked={selectedSuggestionIdSet.has(String(suggestion.id))}
                          onCheckedChange={(checked) => toggleSuggestionSelection(suggestion.id, checked)}
                          disabled={!suggestion.selectable}
                          className="mt-1"
                        />
                        <div className="flex-1 min-w-0">
                          <div className="flex flex-wrap items-center gap-2">
                            <p className="font-semibold">{suggestion.neighborhood}</p>
                            <Badge variant={suggestion.status === 'new' ? 'secondary' : 'outline'}>
                              {formatSuggestionStatusLabel(suggestion.status)}
                            </Badge>
                          </div>
                          <p className="text-sm text-muted-foreground mt-1">
                            {[suggestion.city, suggestion.state].filter(Boolean).join(' / ') || 'Cidade nao identificada'}
                          </p>
                        </div>
                      </div>

                      <div className="grid gap-3 sm:grid-cols-2 text-sm">
                        <div className="rounded-lg border bg-background/80 p-3">
                          <p className="text-xs text-muted-foreground">Distancia aproximada</p>
                          <p className="font-medium">
                            {suggestion.distanceKm == null ? 'n/a' : `${suggestion.distanceKm.toFixed(2)} km`}
                          </p>
                        </div>
                        <div className="rounded-lg border bg-background/80 p-3">
                          <p className="text-xs text-muted-foreground">Origem da sugestao</p>
                          <p className="font-medium">{formatSuggestionSourceLabel(suggestion.suggestionSource)}</p>
                        </div>
                      </div>

                      <div className="rounded-lg border bg-background/80 p-3">
                        <p className="text-xs text-muted-foreground">Motivo da classificacao</p>
                        <p className="text-sm font-medium mt-1">{suggestion.statusReason}</p>
                      </div>

                      {conflictLabels.length > 0 && (
                        <div className="rounded-lg border border-amber-300 bg-amber-50 p-3">
                          <p className="text-xs font-medium text-amber-900">Cobertura relacionada ja existente</p>
                          <div className="flex flex-wrap gap-2 mt-2">
                            {conflictLabels.slice(0, 4).map((label) => (
                              <Badge key={`${suggestion.id}:${label}`} variant="outline" className="border-amber-400 text-amber-900">
                                {label}
                              </Badge>
                            ))}
                          </div>
                        </div>
                      )}

                      <p className="text-xs text-muted-foreground">
                        Origem base: {formatSuggestionOriginLabel(suggestion.suggestionOrigin)}
                      </p>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="space-y-4">
          <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <CheckSquare className="w-5 h-5" />
                Operacao em lote
              </CardTitle>
              <CardDescription>
                Selecione zonas filtradas para ativar, desativar, aplicar taxa/pedido minimo ou excluir em conjunto.
              </CardDescription>
            </div>
            <div className="flex flex-wrap gap-2">
              <Badge variant="secondary">{selectedZoneIds.length} selecionadas</Badge>
              <Button type="button" variant="outline" onClick={() => toggleAllVisible(true)} disabled={visibleZoneIds.length === 0 || allVisibleSelected}>
                Selecionar visiveis
              </Button>
              <Button type="button" variant="outline" onClick={() => setSelectedZoneIds([])} disabled={selectedZoneIds.length === 0}>
                Limpar selecao
              </Button>
            </div>
          </div>
          <div className="grid gap-3 lg:grid-cols-[1.2fr_1fr_1fr_1fr_1fr]">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                placeholder="Buscar bairro..."
                value={searchTerm}
                onChange={(event) => setSearchTerm(event.target.value)}
                className="pl-10"
              />
            </div>
            <Select value={filterStatus} onValueChange={setFilterStatus}>
              <SelectTrigger>
                <Filter className="w-4 h-4 mr-2" />
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Todas</SelectItem>
                <SelectItem value="active">Ativas</SelectItem>
                <SelectItem value="inactive">Inativas</SelectItem>
                <SelectItem value="duplicates">Conflitos</SelectItem>
              </SelectContent>
            </Select>
            <Select value={sourceFilter} onValueChange={setSourceFilter}>
              <SelectTrigger>
                <Layers3 className="w-4 h-4 mr-2" />
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Todas as origens</SelectItem>
                <SelectItem value="manual">Manual</SelectItem>
                <SelectItem value="bulk">Lote</SelectItem>
                <SelectItem value="auto_generated">Auto generated</SelectItem>
              </SelectContent>
            </Select>
            <Select value={sortBy} onValueChange={setSortBy}>
              <SelectTrigger>
                <ArrowUpDown className="w-4 h-4 mr-2" />
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="name_asc">Bairro A-Z</SelectItem>
                <SelectItem value="name_desc">Bairro Z-A</SelectItem>
                <SelectItem value="fee_desc">Maior taxa</SelectItem>
                <SelectItem value="fee_asc">Menor taxa</SelectItem>
                <SelectItem value="min_order_desc">Maior minimo</SelectItem>
                <SelectItem value="status">Status</SelectItem>
                <SelectItem value="source">Origem</SelectItem>
              </SelectContent>
            </Select>
            <div className="grid grid-cols-2 gap-2">
              <Input
                type="number"
                step="0.01"
                value={batchEdit.fee}
                onChange={(event) => setBatchEdit((current) => ({ ...current, fee: event.target.value }))}
                placeholder="Taxa lote"
              />
              <Input
                type="number"
                step="0.01"
                value={batchEdit.min_order}
                onChange={(event) => setBatchEdit((current) => ({ ...current, min_order: event.target.value }))}
                placeholder="Minimo lote"
              />
            </div>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button type="button" variant="outline" onClick={() => applyBatchStatus(true)} disabled={selectedZoneIds.length === 0 || batchUpdateMutation.isPending}>
              Ativar selecionadas
            </Button>
            <Button type="button" variant="outline" onClick={() => applyBatchStatus(false)} disabled={selectedZoneIds.length === 0 || batchUpdateMutation.isPending}>
              Desativar selecionadas
            </Button>
            <Button type="button" onClick={applyBatchValues} disabled={selectedZoneIds.length === 0 || batchUpdateMutation.isPending}>
              Aplicar valores
            </Button>
            <Button type="button" variant="destructive" onClick={deleteSelected} disabled={selectedZoneIds.length === 0 || batchDeleteMutation.isPending}>
              Excluir em lote
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">
            {filteredZones.length === 0 ? (
              <div className="col-span-full">
                <EmptyState
                  icon={MapPin}
                  title="Nenhuma zona encontrada"
                  description={
                    normalizedZones.length === 0
                      ? 'Comece criando bairros manualmente ou via cadastro em lote.'
                      : 'Ajuste busca, filtros ou ordenacao para encontrar as zonas desejadas.'
                  }
                  actionLabel={normalizedZones.length === 0 ? 'Criar zona manual' : 'Nova zona'}
                  onAction={() => setShowModal(true)}
                />
              </div>
            ) : (
              filteredZones.map((zone) => {
                const zoneKey = String(zone.id || `${normalizeNeighborhood(zone.neighborhood)}:${zone.neighborhood}`);
                const hasConflict = duplicateIdSet.has(zoneKey);
                const equivalentZones = hasConflict
                  ? findEquivalentDeliveryZones(normalizedZones, zone.neighborhood, { ignoreId: zone.id })
                  : [];

                return (
                  <div
                    key={zone.id}
                    className={`rounded-xl p-4 shadow-sm border ${
                      hasConflict
                        ? 'border-amber-300 bg-amber-50/50'
                        : zone.is_active
                          ? 'border-green-200 bg-card'
                          : 'border-border bg-card'
                    }`}
                  >
                    <div className="flex items-start justify-between gap-3 mb-4">
                      <div className="flex items-start gap-3 flex-1 min-w-0">
                        <Checkbox
                          checked={selectedIdSet.has(String(zone.id))}
                          onCheckedChange={(checked) => toggleZoneSelection(zone.id, checked)}
                          className="mt-1"
                        />
                        <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center">
                          <MapPin className="w-5 h-5 text-blue-600" />
                        </div>
                        <div className="flex-1 min-w-0 space-y-2">
                          <input
                            key={`${zone.id}:neighborhood:${zone.neighborhood}`}
                            type="text"
                            defaultValue={zone.neighborhood}
                            onBlur={(event) => handleNeighborhoodBlur(zone, event.target.value, event.target)}
                            className="font-semibold text-base bg-transparent border-b border-transparent hover:border-border focus:border-orange-500 focus:outline-none w-full"
                          />
                          <div className="flex flex-wrap gap-2">
                            <Badge variant={zone.is_active ? 'secondary' : 'outline'}>
                              {zone.is_active ? 'Ativa' : 'Inativa'}
                            </Badge>
                            <Badge variant="outline">{formatSourceLabel(zone.source)}</Badge>
                            {hasConflict && (
                              <Badge variant="destructive">Conflito equivalente</Badge>
                            )}
                          </div>
                        </div>
                      </div>
                      <Switch
                        checked={zone.is_active}
                        onCheckedChange={(checked) => updateMutation.mutate({
                          id: zone.id,
                          data: { ...zone, is_active: checked === true },
                          successMessage: checked === true ? 'Zona ativada.' : 'Zona desativada.',
                        })}
                      />
                    </div>

                    {hasConflict && (
                      <div className="mb-4 rounded-lg border border-amber-300 bg-amber-50 p-3">
                        <p className="text-xs font-medium text-amber-900">Cobertura equivalente ja cadastrada</p>
                        <p className="text-xs text-amber-800 mt-1">
                          Equivale a: {equivalentZones.map((item) => item.neighborhood).join(', ')}
                        </p>
                      </div>
                    )}

                    <div className="grid gap-3 md:grid-cols-2">
                      <div>
                        <Label className="text-xs text-muted-foreground">Taxa de entrega</Label>
                        <div className="flex items-center gap-2 mt-1">
                          <span className="text-sm text-muted-foreground">R$</span>
                          <input
                            key={`${zone.id}:fee:${zone.fee}`}
                            type="number"
                            step="0.01"
                            defaultValue={zone.fee}
                            onBlur={(event) => handleNumericBlur(zone, 'fee', event.target.value, event.target)}
                            className="flex-1 px-2 py-1 border rounded text-sm"
                          />
                        </div>
                      </div>
                      <div>
                        <Label className="text-xs text-muted-foreground">Pedido minimo</Label>
                        <div className="flex items-center gap-2 mt-1">
                          <span className="text-sm text-muted-foreground">R$</span>
                          <input
                            key={`${zone.id}:min_order:${zone.min_order ?? ''}`}
                            type="number"
                            step="0.01"
                            defaultValue={zone.min_order ?? ''}
                            onBlur={(event) => handleNumericBlur(zone, 'min_order', event.target.value, event.target, { nullable: true })}
                            className="flex-1 px-2 py-1 border rounded text-sm"
                          />
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center justify-between pt-4 mt-4 border-t">
                      <div>
                        <p className="text-xs text-muted-foreground">Resumo</p>
                        <p className="text-lg font-bold text-green-600">{formatCurrency(zone.fee)}</p>
                      </div>
                      <Button
                        size="icon"
                        variant="ghost"
                        className="h-8 w-8 text-red-500 hover:text-red-700"
                        onClick={() => {
                          if (window.confirm(`Excluir a zona "${zone.neighborhood}"?`)) {
                            deleteMutation.mutate(zone.id);
                          }
                        }}
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </CardContent>
      </Card>

      <Dialog
        open={showModal}
        onOpenChange={(open) => {
          if (open) {
            setShowModal(true);
            return;
          }
          closeModal();
        }}
      >
        <DialogContent className="sm:max-w-sm max-w-[95vw]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <MapPin className="w-5 h-5" />
              Nova zona manual
            </DialogTitle>
          </DialogHeader>

          <form onSubmit={handleSingleCreate} className="space-y-4">
            <div>
              <Label>Nome do bairro</Label>
              <Input
                value={formData.neighborhood}
                onChange={(event) => setFormData((current) => ({ ...current, neighborhood: event.target.value }))}
                placeholder="Ex: Centro, Jardins..."
                required
              />
              {formData.neighborhood && findEquivalentDeliveryZones(normalizedZones, formData.neighborhood).length > 0 && (
                <p className="text-xs text-amber-700 mt-2 flex items-center gap-1">
                  <AlertTriangle className="w-3 h-3" />
                  Ja existe uma zona equivalente para esse bairro.
                </p>
              )}
            </div>

            <div>
              <Label>Taxa de entrega (R$)</Label>
              <Input
                type="number"
                step="0.01"
                value={formData.fee}
                onChange={(event) => setFormData((current) => ({ ...current, fee: event.target.value }))}
                placeholder="0.00"
                required
              />
            </div>

            <div>
              <Label>Pedido minimo do bairro (R$)</Label>
              <Input
                type="number"
                step="0.01"
                value={formData.min_order}
                onChange={(event) => setFormData((current) => ({ ...current, min_order: event.target.value }))}
                placeholder="Opcional"
              />
            </div>

            <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
              <div>
                <Label>Zona ativa</Label>
                <p className="text-xs text-muted-foreground">Origem: manual</p>
              </div>
              <Switch
                checked={formData.is_active}
                onCheckedChange={(checked) => setFormData((current) => ({ ...current, is_active: checked === true }))}
              />
            </div>

            <div className="flex gap-3 pt-2">
              <Button type="button" variant="outline" onClick={closeModal} className="flex-1">
                Cancelar
              </Button>
              <Button type="submit" className="flex-1 bg-orange-500 hover:bg-orange-600" disabled={createMutation.isPending}>
                Criar
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}
